import {centralDay} from './qc-rules';
export const REFERENCE_DEPARTMENTS=['Aurora','Camden County','Carthage','Dallas County','Greene County','Laclede County','LL1 Branson','LL2 St. Robert','LL4 Ft Smith','LL5 NW Arkansas','Mount Vernon','Mountain View','Neonatal Transport Team','Perryville','Shannon County','South Barry','Stone County','Wright County','POC Test','Lifeline Adm: Orientation'];
export function centralDayBounds(day:string){
 const midnight=(d:string)=>{const target=Date.parse(d+'T00:00:00Z');let t=target;for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',timeZoneName:'longOffset'}).formatToParts(new Date(t));const name=parts.find(p=>p.type==='timeZoneName')?.value||'GMT';const m=name.match(/GMT([+-])(\d{2}):(\d{2})/);const offset=m?(m[1]==='-'?-1:1)*(Number(m[2])*60+Number(m[3]))*60000:0;t=target-offset}return new Date(t).toISOString()};
 const next=new Date(Date.parse(day+'T12:00:00Z')+86400000).toISOString().slice(0,10);return {start:midnight(day),end:midnight(next)};
}
export function departmentFor(snapshot:any){return snapshot.department?.label||'Unassigned legacy records'}
export function groupDailyRecords(records:any[]){const groups=new Map<string,any[]>();const all=new Map(records.map(r=>[r.id,r]));
 const root=(r:any)=>{if(r.snapshot.input.seriesId)return r.snapshot.input.seriesId;let current=r,seen=new Set([r.id]);while(current.snapshot.input.repeatOf){const parent=current.snapshot.input.repeatOf;if(seen.has(parent))break;seen.add(parent);if(!all.has(parent))return parent;current=all.get(parent)}return current.id};
 for(const r of [...records].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id))){const key=root(r)+'|'+(r.snapshot.department?.id||'legacy');groups.set(key,[...(groups.get(key)||[]),r])}return [...groups.entries()].map(([id,attempts])=>{attempts.sort((a,b)=>Number(!!a.snapshot.input.repeatOf)-Number(!!b.snapshot.input.repeatOf)||a.occurred_at.localeCompare(b.occurred_at)||a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));return {id,attempts,department:departmentFor(attempts[0].snapshot),continued:!!attempts[0].snapshot.input.repeatOf}});
}
export function dailyCsv(records:any[],exceptions:any[],departments:any[],day:string,endDay=day){
 const safe=(v:any)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};
 const out:any[][]=[['EMS Glucose Control Log Report - All Departments'],['Report start date (Central)',day],['Report end date (Central, inclusive)',endDay],[],['Department','QC sessions','QC attempts','Open exceptions']];
 const groups=groupDailyRecords(records);const labels=[...new Set([...departments.map(d=>d.label),...groups.map(g=>g.department),...exceptions.map(e=>e.departmentLabel).filter(Boolean)])].sort();
 for(const label of labels)out.push([label,groups.filter(g=>g.department===label).length,records.filter(r=>departmentFor(r.snapshot)===label).length,exceptions.filter(e=>e.departmentLabel===label&&e.status!=='closed').length]);
 out.push(['Total',groups.length,records.length,exceptions.filter(e=>e.status!=='closed').length],[],['Department','User ID / email','Recorded Date (Central)','Truck','Glucometer Serial Number','Level 1 QC','Level 3 QC','QC Result First Test','Level 1 QC (repeat test, if needed)','Level 3 QC (repeat test, if needed)','QC Result Repeat Test','Comments','Record ID','Linked initial record ID','Attempt','Strip lot','Level 1 control lot','Level 3 control lot','Level 1 range','Level 3 range','Units','Exception status','Record source','Original source file','Temperature recording','Temperature observed date','Temperature source QC record','Temperature source record','Temperature high (F)','Temperature low (F)','Temperature current (F)','Temperature result','Temperature corrective measure','Truck identification type','Original truck value','User identification type','Original user ID']);
 const reading=(r:any,l:string)=>r.snapshot.input[l+'Error']||r.snapshot.input[l+'Value'];
 const result=(r:any)=>r.snapshot.historical?(r.snapshot.provenance.reportedResult||'Not recorded in source'):r.status==='pass'?'Both QC are in range':r.snapshot.issues.join('; ');
 for(const g of groups){for(const r of g.attempts){const s=r.snapshot,isRepeat=!!s.input.repeatOf;out.push([g.department,s.operator.identifier||s.operator.networkId||s.operator.email||'Not recorded',new Date(r.occurred_at).toLocaleString('en-US',{timeZone:'America/Chicago'}),s.truck.label,s.device.serial,isRepeat?'':reading(r,'low'),isRepeat?'':reading(r,'high'),isRepeat?'':result(r),isRepeat?reading(r,'low'):'',isRepeat?reading(r,'high'):'',isRepeat?result(r):'',s.input.notes||'',r.id,s.input.seriesId||s.input.repeatOf||r.id,isRepeat?'Repeat':'Initial',s.strip.lot,s.low.lot,s.high.lot,s.lowRange?`${s.lowRange.min}–${s.lowRange.max}`:'Not configured',s.highRange?`${s.highRange.min}–${s.highRange.max}`:'Not configured',s.lowRange?.units||'',exceptions.filter(e=>e.record_id===r.id).map(e=>e.status).join('; '),s.historical?'Historical import':'Recorded in ClinicalQC',s.provenance?.filename||'',s.temperatureCapture?.mode||(s.temperature?'recorded':'not_recorded'),s.temperature?.observedDate||'',s.temperatureCapture?.sourceQcRecordId||s.temperature?.qcRecordId||'',s.temperatureCapture?.sourceTemperatureRecordId||'',s.temperature?.high??'',s.temperature?.low??'',s.temperature?.current??'',s.temperature?.status||(s.temperatureCapture?.mode==='disabled'?'Recording disabled':'Not recorded'),s.temperature?.correctiveAction||'',s.truck.isPlaceholder?'Administrative placeholder; original truck unknown':s.truck.label==='Not recorded'?'Not recorded in source':'Recorded truck',s.truck.isPlaceholder?(s.provenance?.truckPlaceholder?.originalTruck?.label||'Not recorded'):s.truck.label,s.operator.isPlaceholder?'Administrative placeholder; original user unresolved':'Recorded user ID',s.provenance?.originalNetworkId||s.operator.networkId||''])}}
 return '\uFEFF'+out.map(row=>row.map(safe).join(',')).join('\r\n');
}
