import assert from 'node:assert/strict';
import {runHistoryQueue} from '../lib/history-queue.ts';
const item=id=>({id,name:id+'.csv',text:id,state:'ready',preview:{fileHash:id}});
let queue=[item('a'),item('b'),item('c')],calls=[],saved=new Set(),paused=false;
const update=(id,p)=>{queue=queue.map(q=>q.id===id?{...q,...p}:q)};
const send=async(action,q)=>{calls.push(action+q.id);if(action==='preview')return {fileHash:q.id,newRows:saved.has('shared')?0:1,duplicates:saved.has('shared')?1:0,errors:[]};saved.add('shared');return {imported:1,skipped:0}};
let r=await runHistoryQueue(queue,send,update,()=>paused);
assert.deepEqual(calls,['previewa','importa','previewb','previewc']);assert.equal(queue[0].state,'done');assert.equal(queue[1].state,'skipped');assert.equal(r.completed,3);
queue=[item('a'),item('b')];calls=[];
r=await runHistoryQueue(queue,async(action,q)=>{calls.push(action+q.id);if(action==='preview')return {fileHash:q.id,newRows:1,errors:[]};throw Error('Connection lost after sending');},update,()=>false);
assert.equal(r.error,true);assert.deepEqual(calls,['previewa','importa']);assert.equal(queue[0].state,'error');assert.equal(queue[1].state,'ready');
queue=[item('a'),item('b')];calls=[];paused=false;
r=await runHistoryQueue(queue,async(action,q)=>{calls.push(action+q.id);if(action==='preview')return {fileHash:q.id,newRows:1,errors:[]};paused=true;return {imported:1}},update,()=>paused);
assert.equal(r.paused,true);assert.equal(queue[0].state,'done');assert.equal(queue[1].state,'ready');assert.deepEqual(calls,['previewa','importa']);
queue=[item('a')];calls=[];
r=await runHistoryQueue(queue,async(action,q)=>{calls.push(action);return {fileHash:q.id,newRows:1,errors:['Conflict discovered during recheck']}},update,()=>false);
assert.deepEqual(calls,['preview']);assert.equal(r.error,true);
queue=[item('a')];r=await runHistoryQueue(queue,async()=>({fileHash:'changed',newRows:1,errors:[]}),update,()=>false);assert.equal(r.error,true);
queue=[item('a')];paused=false;calls=[];r=await runHistoryQueue(queue,async()=>{paused=true;return {fileHash:'a',newRows:1,errors:[]}},update,()=>paused);assert.equal(queue[0].state,'ready');assert.equal(r.paused,true);
console.log('Historical queue tests passed: sequential duplicate rechecks, failures, pause, changed preview, and conflicts.');
