import {operator,rows,one,decode,Problem,db,required,date} from '@/lib/server';
import {temperatureStatements} from '@/lib/temperature-server';
import {getTemperatureSettings} from '@/lib/temperature-settings';
import {centralDay} from '@/lib/qc-rules';
export const dynamic='force-dynamic';
const json=(v:any,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
const fail=(e:any)=>json({error:e instanceof Problem?e.message:'The temperature record could not be saved. Please try again.'},e instanceof Problem?e.code:500);
export async function GET(req:Request){try{const me=await operator(),reviewer=['admin','supervisor'].includes(me.role);const selected=new URL(req.url).searchParams.get('date')||centralDay();date(selected,'temperature date');const rr=reviewer?await rows('SELECT * FROM temperature_records WHERE observed_date=? ORDER BY created_at DESC',selected):await rows('SELECT * FROM temperature_records WHERE observed_date=? AND operator_id=? ORDER BY created_at DESC',selected,me.id);return json({records:rr.map(r=>({...r,snapshot:JSON.parse(r.snapshot)})),date:selected,temperatureSettings:await getTemperatureSettings()})}catch(e){return fail(e)}}
export async function POST(req:Request){try{const me=await operator();const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Problem('Refresh this page and try again.',403);const text=await req.text();if(text.length>16000)throw new Problem('Temperature entry is too long.');const b=JSON.parse(text);required(b.requestId,'Submission ID');const existing=await one('SELECT id,operator_id FROM temperature_records WHERE id=?',b.requestId);if(existing){if(existing.operator_id!==me.id)throw new Problem('Invalid submission ID.',409);return json({ok:true,id:existing.id})}if(!(await getTemperatureSettings()).storageEnabled)throw new Problem('Office and supply storage temperature recording is turned off by an administrator.',403);const locationRow=await one("SELECT * FROM assets WHERE id=? AND kind='location' AND active=1",b.locationId);if(!locationRow)throw new Problem('Select an active supply storage location.');const observedDate=date(b.date,'reading date')!;if(observedDate>centralDay())throw new Problem('Temperature date cannot be in the future.');const built=temperatureStatements(b,decode(locationRow),me,observedDate,null,b.requestId);await db().batch(built.statements);return json({ok:true,id:b.requestId,status:built.snapshot.status})}catch(e){return fail(e)}}
