 'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
export default function LoginInvitation({person}:{person:Record<string,any>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[invite,setInvite]=useState<{url:string;email:string;expiresAt:string}|null>(null),[copied,setCopied]=useState(false);
 if(person.login_enabled)return <span className="badge green">Login active</span>;
 return <><Button variant="outline" size="sm" disabled={!person.active} onClick={()=>{setOpen(true);setError('');}}>Set up login</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent className="overflow-y-auto p-6"><SheetHeader><SheetTitle>Staff login · {person.name}</SheetTitle><SheetDescription>Create an invitation for {person.email}. The person must verify this email address to activate their login.</SheetDescription></SheetHeader><div className="stack mt-6"><p>Creating a new invitation replaces any unused invitation for this person. Invitations expire after seven days.</p>{error&&<p className="notice bad" role="alert">{error}</p>}{invite?<><label className="field"><span>Invitation link</span><Input readOnly value={invite.url} onFocus={e=>e.target.select()}/></label><Button onClick={async()=>{try{await navigator.clipboard.writeText(invite.url);setCopied(true);}catch{setError('Select and copy the invitation link above.');}}}>{copied?'Copied':'Copy invitation link'}</Button><p className="text-sm">Share this link directly with {invite.email}. No invitation email has been sent.</p></>:<Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operatorId:person.id})});const data=await r.json() as any;if(!r.ok)throw Error(data.error);setInvite(data);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Creating…':'Create invitation link'}</Button>}</div></SheetContent></Sheet></>;
}
