import {excludedHistoricalDepartment,historicalScopeLabel} from './history-scope';
import {centralDay} from './qc-rules';
import {parseLegacyReport,legacyKey,sha256,reportedOutcome,type LegacyEntry} from './history-parser';
import {Problem,db,stmt,rows,one,uid,now,auditStmt,decode} from './server';
const identityKey=(e:LegacyEntry)=>sha256(JSON.stringify([e.department.trim().toLowerCase(),e.networkId,e.occurredAt]));
export async function previewImport(text:string,filename:string){
 if(typeof text!=='string'||text.length>1000000)throw new Problem('Upload a CSV no larger than 1 MB.');if(!filename.toLowerCase().endsWith('.csv'))throw new Problem('Upload the Qualtrics CSV report. For an Excel workbook, use Save As → CSV first.');
 const parsed=parseLegacyReport(text),fileHash=await sha256(text),existingBatch=await one('SELECT * FROM import_batches WHERE file_hash=?',fileHash);
 const excludedEntries=parsed.entries.filter(e=>excludedHistoricalDepartment(e.department));
 parsed.warnings.unshift(historicalScopeLabel+` ${excludedEntries.length} source rows will be skipped.`);
 const keyed=await Promise.all(parsed.entries.filter(e=>!excludedHistoricalDepartment(e.department)).map(async entry=>({entry,fingerprint:await legacyKey(entry),identity:await identityKey(entry)})));
 const identities=[...new Set(keyed.map(k=>k.identity))],found:any[]=[];for(let i=0;i<identities.length;i+=50){const chunk=identities.slice(i,i+50);found.push(...await rows(`SELECT * FROM history_rows WHERE identity_key IN (${chunk.map(()=>'?').join(',')})`,...chunk))}
 const byIdentity=new Map(found.map(r=>[r.identity_key,r.fingerprint])),seen=new Map<string,string>();let duplicates=0;const pending:typeof keyed=[];
 for(const k of keyed){const match=byIdentity.get(k.identity)||seen.get(k.identity);if(match===k.fingerprint){duplicates++;continue}if(match){parsed.errors.push(`Row ${k.entry.sourceRow}: another entry has the same department, Network ID, and timestamp but different readings or comments. Review this conflict before importing.`);continue}seen.set(k.identity,k.fingerprint);pending.push(k)}
 return {fileHash,filename,sourceRows:parsed.entries.length,excludedRows:excludedEntries.length,excludedDepartments:[...new Set(excludedEntries.map(e=>e.department))],duplicates,newRows:pending.length,attempts:pending.reduce((n,k)=>n+1+(k.entry.repeatLow||k.entry.repeatHigh||k.entry.repeatResult?1:0),0),errors:parsed.errors,warnings:parsed.warnings,departments:parsed.departments.filter(d=>!excludedHistoricalDepartment(d.name)),entries:keyed.map(k=>({...k.entry,duplicate:byIdentity.get(k.identity)===k.fingerprint})),existingBatch:existingBatch?decode(existingBatch):null,pending};
}
export async function importHistory(text:string,filename:string,actor:{id:string,name:string},expectedHash?:string){
 const p=await previewImport(text,filename);if(expectedHash&&p.fileHash!==expectedHash)throw new Problem('The file changed after preview. Preview it again.',409);if(p.errors.length)throw new Problem(p.errors.join('\n'));if(p.existingBatch)return {ok:true,alreadyImported:true,batch: p.existingBatch,imported:0,skipped:p.sourceRows};
 const ts=now(),batchId=uid();const known=await rows("SELECT * FROM assets WHERE kind='department'");const departmentIds=new Map(known.map(d=>[d.label.trim().toLowerCase(),d.id]));const ops:any[]=[];
 for(const name of [...new Set([...p.departments.map(d=>d.name),...p.pending.map(k=>k.entry.department)])]){const key=name.trim().toLowerCase();if(!departmentIds.has(key)){const id=uid();departmentIds.set(key,id);ops.push(stmt('INSERT INTO assets (id,kind,asset_key,label,details,active,revision) VALUES (?,?,?,?,?,1,1)',id,'department',key,name,JSON.stringify({source:'Historical report import'})))}}
 let recordCount=0;
 for(const k of p.pending){const e=k.entry,firstId='history-'+k.fingerprint+'-1',departmentId=departmentIds.get(e.department.toLowerCase())!,operatorId='historical:'+await sha256(e.networkId);ops.push(stmt('INSERT INTO history_rows (fingerprint,identity_key,batch_id,record_id,source_row) VALUES (?,?,?,?,?)',k.fingerprint,k.identity,batchId,firstId,e.sourceRow));
 const attempts=[{number:1,low:e.low,high:e.high,result:e.result},...(e.repeatLow||e.repeatHigh||e.repeatResult?[{number:2,low:e.repeatLow,high:e.repeatHigh,result:e.repeatResult}]:[])];
 for(const a of attempts){const id='history-'+k.fingerprint+'-'+a.number;const status=reportedOutcome(a.result);const missing=['Device serial number','Truck','Strip lot','Control lots','Manufacturer ranges','Units','Competency evidence'];const reasons=status==='historical_exception'?[a.result||'Historical QC exception']:status==='historical_unverified'?['Historical result needs review']:[];if(!a.low||!a.high)reasons.push('One or both control readings were not recorded');
 const value=(raw:string)=>raw!==''&&/^\d+(\.\d+)?$/.test(raw)?Number(raw):null;
 const supply={id:'',label:'Not recorded in source',lot:'Not recorded',expires:null,discard:null};
 const snapshot={historical:true,provenance:{batchId,filename,fileHash:p.fileHash,sourceRow:e.sourceRow,originalNetworkId:e.originalNetworkId,originalDate:e.recordedDate,raw:e.raw,reportedResult:a.result,importedAt:ts,importedBy:actor.name,missing,repeatTimeKnown:a.number===1},department:{id:departmentId,label:e.department},device:{id:'',label:'Historical device · not identified',serial:'Not recorded',model:'Not recorded'},truck:{id:'',label:'Not recorded'},strip:supply,low:supply,high:supply,lowRange:null,highRange:null,operator:{id:operatorId,name:e.originalNetworkId.trim(),networkId:e.networkId,credentialStatus:'not_recorded',expires:null,credentialRef:'Not recorded in source'},input:{networkId:e.networkId,departmentId,occurredAt:e.occurredAt,lowValue:value(a.low),highValue:value(a.high),lowError:value(a.low)===null?a.low:'',highError:value(a.high)===null?a.high:'',clean:null,stored:null,attested:null,notes:e.comments,seriesId:firstId,...(a.number===2?{repeatOf:firstId}: {})},status,issues:reasons,lowResult:'not_verified',highResult:'not_verified'};
 ops.push(stmt('INSERT INTO records (id,operator_id,device_id,occurred_at,created_at,status,snapshot) VALUES (?,?,?,?,?,?,?)',id,operatorId,'historical-unidentified:'+k.fingerprint,e.occurredAt,ts,status,JSON.stringify(snapshot)));recordCount++;
 if(reasons.length)ops.push(stmt('INSERT INTO exceptions (id,record_id,operator_id,category,title,status,created_at,updated_at,details) VALUES (?,?,?,?,?,?,?,?,?)',uid(),id,operatorId,'historical','Historical review: '+reasons[0],'open',ts,ts,JSON.stringify({issues:reasons,historical:true,operatorName:e.originalNetworkId.trim(),departmentId,departmentLabel:e.department,sourceDate:e.recordedDate,filename})))
 }
 }
 const details={excludedRows:p.excludedRows,excludedDepartments:p.excludedDepartments,scopePolicy:historicalScopeLabel,dates:[...new Set(p.entries.map(e=>centralDay(new Date(e.occurredAt))))].sort(),warnings:p.warnings,duplicateRule:'Same department, normalized Network ID, source timestamp, readings, outcomes, and comments. Conflicting content at the same department/Network ID/time is rejected.'};
 ops.push(stmt('INSERT INTO import_batches (id,file_hash,filename,created_at,actor_id,actor_name,source_rows,imported_rows,skipped_rows,record_count,details) VALUES (?,?,?,?,?,?,?,?,?,?,?)',batchId,p.fileHash,filename,ts,actor.id,actor.name,p.sourceRows,p.newRows,p.duplicates+p.excludedRows,recordCount,JSON.stringify(details)),auditStmt(actor,batchId,'Historical QC report imported',{filename,fileHash:p.fileHash,sourceRows:p.sourceRows,importedRows:p.newRows,skippedRows:p.duplicates,excludedRows:p.excludedRows,recordCount}));
 try{await db().batch(ops)}catch(e:any){if(String(e.message).includes('UNIQUE')){const winner=await one('SELECT * FROM import_batches WHERE file_hash=?',p.fileHash);if(winner)return {ok:true,alreadyImported:true,batch:decode(winner),imported:0,skipped:p.sourceRows};throw new Problem('Another import changed these records. Preview the file again.',409)}throw e}
 return {ok:true,alreadyImported:false,imported:p.newRows,skipped:p.duplicates,excluded:p.excludedRows,recordCount,batch:{id:batchId,filename,created_at:ts,...details}};
}
