import {excludedHistoricalDepartment} from './history-scope';
export type LegacyEntry={department:string;networkId:string;originalNetworkId:string;recordedDate:string;occurredAt:string;low:string;high:string;result:string;repeatLow:string;repeatHigh:string;repeatResult:string;comments:string;sourceRow:number;raw:string[];serial?:string;truck?:string;lowSupply?:string;highSupply?:string;stripSupply?:string;headers?:string[];extended?:boolean};
export type LegacyReport={entries:LegacyEntry[];departments:{name:string;count:number}[];errors:string[];warnings:string[];declaredTotal:number|null;reportTitle:string};
export function parseCsv(text:string):string[][]{const rows:string[][]=[];let row:string[]=[],field='',quoted=false;const input=text.replace(/^\uFEFF/,'');for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){field+='"';i++}else if(quoted){quoted=false}else if(field===''){quoted=true}else throw new Error('Invalid CSV quoting. Export the report as CSV and try again.')}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){row.push(field);rows.push(row);row=[];field='';if(c==='\r'&&input[i+1]==='\n')i++}else field+=c}if(quoted)throw new Error('A quoted CSV field is incomplete.');if(field!==''||row.length){row.push(field);rows.push(row)}return rows}
export function parseLegacyDate(raw:string){const m=raw.trim().match(/^([A-Za-z]{3})\s+(\d{1,2})\s+(\d{4})\s+(\d{1,2}):(\d{2})\s*(am|pm)\s+(CST|CDT)$/i);if(!m)throw new Error('Unrecognized date or missing CST/CDT time zone: '+raw);const months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'],month=months.indexOf(m[1].toLowerCase()),day=+m[2],year=+m[3],hour=+m[4],minute=+m[5];if(month<0||hour<1||hour>12||minute>59||day<1||day>31)throw new Error('Invalid date: '+raw);const midnight=new Date(Date.UTC(year,month,day));if(midnight.getUTCMonth()!==month)throw new Error('Invalid calendar date: '+raw);return new Date(Date.UTC(year,month,day,hour%12+(m[6].toLowerCase()==='pm'?12:0)+(m[7].toUpperCase()==='CST'?6:5),minute)).toISOString()}
export function reportedOutcome(raw:string):'historical_pass'|'historical_exception'|'historical_unverified'{const v=raw.trim().toLowerCase().replace(/\s+/g,' ');if(v==='both qc are in range'||v==='both qc in range')return 'historical_pass';if(v==='i need to log another qc'||/out of range|outside.*range|not.*in range|fail|error/.test(v))return 'historical_exception';return 'historical_unverified'}
export function parseLegacyReport(text:string):LegacyReport{
 const result:LegacyReport={entries:[],departments:[],errors:[],warnings:[],declaredTotal:null,reportTitle:''};let rows:string[][];try{rows=parseCsv(text)}catch(e:any){result.errors.push(e.message);return result}result.reportTitle=rows.find(r=>r.some(c=>c.trim()))?.[0]?.trim()||'';
 let summary=false,department='',heading='',headers:string[]|null=null;let sawHeader=false,summarySeen=false;
 const needed=['Network ID','Recorded Date','Level 1 QC','Level 3 QC','QC Result First Test','Level 1 QC (second test, if needed)','Level 3 QC (second test, if needed)','QC Result Second Test','Comments'];
 for(let index=0;index<rows.length;index++){const row=rows[index],trim=row.map(c=>c.trim());if(trim.every(c=>!c)){headers=null;summary=false;continue}
 if(trim[0]==='Answer'&&trim[1]==='Count'){summary=!summarySeen&&(/Select Department/i.test(heading)||!sawHeader);if(summary)summarySeen=true;headers=null;continue}
 if(summary){if(trim.length>=2&&/^\d+$/.test(trim[1])){if(trim[0]==='Total')result.declaredTotal=Number(trim[1]);else result.departments.push({name:trim[0],count:Number(trim[1])});continue}summary=false}
 if(trim[0]==='Network ID'){headers=trim;sawHeader=true;const missing=needed.filter(h=>!headers!.includes(h));if(missing.length)result.errors.push(`Row ${index+1}: missing columns ${missing.join(', ')}.`);if(!department&&!headers.includes('Select Department'))result.errors.push(`Row ${index+1}: missing department section heading.`);continue}
 if(headers){const get=(name:string)=>row[headers!.indexOf(name)]||'';if(row.length>headers.length&&row.slice(headers.length).some(c=>c.trim()))result.errors.push(`Row ${index+1}: unexpected extra data columns.`);const rowDepartment=headers.includes('Select Department')?get('Select Department').trim():department;const excluded=excludedHistoricalDepartment(rowDepartment);if(!rowDepartment)result.errors.push(`Row ${index+1}: department is missing.`);const networkId=get('Network ID').trim();if(!networkId&&!excluded)result.errors.push(`Row ${index+1}: Network ID is missing.`);let occurredAt='';try{occurredAt=parseLegacyDate(get('Recorded Date'))}catch(e:any){if(!excluded)result.errors.push(`Row ${index+1}: ${e.message}`)}
 const extended=headers.includes('Select Department');
 const selected=(prefix:string)=>{const cells=headers!.map((h,i)=>({h,v:(row[i]||'').trim()})).filter(c=>c.h.startsWith(prefix)&&c.v);if(cells.length>1&&!excluded)result.errors.push(`Row ${index+1}: multiple ${prefix} selections. Resolve before importing.`);return cells[0]?.v||'';};
 if(!excluded&&occurredAt&&!/^[A-Za-z]{3}\s+\d{1,2}\s+2026\s/.test(get('Recorded Date')))result.errors.push(`Row ${index+1}: only 2026 historical records are supported.`);
 result.entries.push({department:rowDepartment,networkId:networkId.toLowerCase(),originalNetworkId:get('Network ID'),recordedDate:get('Recorded Date'),occurredAt,low:get('Level 1 QC').trim(),high:get('Level 3 QC').trim(),result:get('QC Result First Test').trim(),repeatLow:get('Level 1 QC (second test, if needed)').trim(),repeatHigh:get('Level 3 QC (second test, if needed)').trim(),repeatResult:get('QC Result Second Test').trim(),comments:get('Comments'),sourceRow:index+1,raw:row,headers:[...headers],extended,serial:selected('Glucometer SN - '),truck:selected('Ambulance Number/Supervisor Vehicle - '),lowSupply:get('Level 1 QC Lot Number | Printed Expiration Date | QC Range').trim(),highSupply:get('Level 3 QC Lot Number | Printed Expiration Date | QC Range').trim(),stripSupply:get('StatStrip Glucose Test Strip Lot Number | Printed Expiration Date').trim()});continue}
 if(trim.length===1||trim.slice(1).every(c=>!c)){heading=trim[0];if(result.departments.some(d=>d.name===heading)||rows[index+1]?.[0]?.trim()==='Network ID')department=heading;}
 }
 if(!sawHeader)result.errors.push('No supported department report tables found. Upload the Qualtrics daily report CSV.');if(!result.entries.length)result.errors.push('This report contains no QC entries to import.');if(result.entries.length>500)result.errors.push('Import up to 500 report rows per file. Split larger reports into smaller CSV files.');
 if(result.declaredTotal!==null&&result.entries.length!==result.declaredTotal)result.errors.push(`Report total is ${result.declaredTotal}, but ${result.entries.length} rows were found.`);
 for(const d of result.departments){const found=result.entries.filter(e=>e.department===d.name).length;if(found!==d.count)result.errors.push(`${d.name}: summary says ${d.count} entries, but ${found} rows were found.`)}
 const missing=result.entries.filter(e=>!e.low||!e.high).length;if(missing)result.warnings.push(`${missing} first-test rows have missing readings; their source values will be retained.`);
 const unknown=result.entries.filter(e=>reportedOutcome(e.result)==='historical_unverified').length;if(unknown)result.warnings.push(`${unknown} rows have an unrecognized result and will be marked for historical review.`);
 if(result.entries.some(e=>e.extended))result.warnings.push('Serial numbers, trucks, lots, expiration dates and reference ranges are retained from each source row. Current device assignments and testing credentials are unchanged.');else result.warnings.push('This report has no equipment or supply columns; those details will be marked not recorded.');return result;
}
export async function sha256(text:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function legacyKey(e:LegacyEntry){return await sha256(JSON.stringify([e.department.trim().toLowerCase(),e.networkId,e.occurredAt,e.low,e.high,e.result,e.repeatLow,e.repeatHigh,e.repeatResult,e.comments.trim(),...(e.extended?[e.serial,e.truck,e.lowSupply,e.highSupply,e.stripSupply]:[])]))}
