import {exceptionRepeatSql,repeatSummary} from '@/lib/exception-repeats';
import {reviewNotes} from '@/lib/review-decisions';
import { NextResponse } from 'next/server';
import { Problem,db,stmt,rows,one,decode,uid,now,auditStmt,identity,operator,admin,review,required,date } from '@/lib/server';
import { credentialValid,centralDay,evaluateQC } from '@/lib/qc-rules';
import {deviceModelKey,sameDeviceModel} from '@/lib/device-model';
import {REGIONS,normalizeRegion} from '@/lib/regions';
import {meterSerialKey} from '@/lib/meter-register';
import {controlRange} from '@/lib/control-ranges';
import {getTemperatureSettings,saveTemperatureSettings} from '@/lib/temperature-settings';
import {qcTemperature} from '@/lib/qc-temperature';
import {qcDeviceLocationStatements} from '@/lib/qc-device-location';
import {closeExceptionAndRelease} from '@/lib/exception-release';
import {REFERENCE_DEPARTMENTS,centralDayBounds,dailyCsv} from '@/lib/report';
export const dynamic='force-dynamic';
const json=(data:any,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
function fail(e:any){console.error('ClinicalQC request failed',e.message);return json({error:e instanceof Problem?e.message:e.message?.includes('UNIQUE constraint')?'That serial number, lot, email, Network ID, or range already exists.': 'The request could not be saved. Your entries are still here. Please try again.'},e instanceof Problem?e.code:500)}
export async function GET(req?:Request){try{
 await identity();
 const me=await operator(),isReviewer=['admin','supervisor'].includes(me.role);
 const params=req?new URL(req.url).searchParams:null;
 if(params&&(params.has('reportStart')||params.has('reportEnd')||params.has('reportDate'))){
 review(me);const ranged=params.has('reportStart')||params.has('reportEnd');
 const startDate=date(ranged?params.get('reportStart'):params.get('reportDate'),'report start date')!,endDate=date(ranged?params.get('reportEnd'):params.get('reportDate'),'report end date')!;
 if(startDate>endDate)throw new Problem('Report end date must be on or after the start date.');
 const start=centralDayBounds(startDate).start,end=centralDayBounds(endDate).end;
 const rr=await rows("SELECT * FROM records WHERE status NOT IN ('historical_superseded','historical_excluded') AND occurred_at>=? AND occurred_at<? ORDER BY occurred_at DESC, rowid DESC LIMIT 5001",start,end);if(rr.length>5000)throw new Problem('This date range has more than 5,000 attempts. Choose a smaller date range to view or export the complete report.',413);
 const reportRecords=rr.map(r=>({...r,snapshot:JSON.parse(r.snapshot)}));const reportExceptions=(await rows("SELECT e.* FROM exceptions e LEFT JOIN records r ON r.id=e.record_id WHERE e.status!='excluded' AND ((r.status NOT IN ('historical_superseded','historical_excluded') AND r.occurred_at>=? AND r.occurred_at<?) OR (e.record_id IS NULL AND e.created_at>=? AND e.created_at<?))",start,end,start,end)).map(decode);
 const departments=(await rows("SELECT * FROM assets WHERE kind='department' ORDER BY label")).map(decode);
 if(params.get('format')==='csv')return new Response(dailyCsv(reportRecords,reportExceptions,departments,startDate,endDate),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="ClinicalQC-Report-${startDate}${startDate===endDate?'':'-through-'+endDate}.csv"`,'Cache-Control':'no-store'}});
 return json({date:startDate===endDate?startDate:null,startDate,endDate,records:reportRecords,exceptions:reportExceptions,departments});
 }
 const [assets,users,records,exceptions,actions,audit,temperatureSettings]=await Promise.all([
 rows('SELECT * FROM assets ORDER BY label'), isReviewer?rows('SELECT o.*, EXISTS(SELECT 1 FROM qc_login_links l WHERE l.operator_id=o.id) AS login_enabled FROM operators o ORDER BY name'):rows('SELECT * FROM operators WHERE id=?',me.id),
 isReviewer?rows("SELECT * FROM records WHERE status NOT IN ('historical_superseded','historical_excluded') ORDER BY occurred_at DESC, created_at DESC LIMIT 500"):rows("SELECT * FROM records WHERE status NOT IN ('historical_superseded','historical_excluded') AND operator_id=? ORDER BY occurred_at DESC, created_at DESC LIMIT 500",me.id),
 isReviewer?rows("SELECT * FROM exceptions WHERE status!='excluded' ORDER BY created_at DESC LIMIT 1000"):rows("SELECT * FROM exceptions WHERE status!='excluded' AND operator_id=? ORDER BY created_at DESC LIMIT 500",me.id),
 isReviewer?rows("SELECT a.* FROM actions a JOIN exceptions e ON e.id=a.exception_id WHERE e.status!='excluded' ORDER BY a.created_at DESC LIMIT 2000"):rows("SELECT a.* FROM actions a JOIN exceptions e ON e.id=a.exception_id WHERE e.status!='excluded' AND e.operator_id=? ORDER BY a.created_at DESC LIMIT 500",me.id),
 me.role==='admin'?rows('SELECT * FROM audit ORDER BY created_at DESC LIMIT 300'):Promise.resolve([]),getTemperatureSettings()
 ]);
 const repeatByException=new Map<string,any>();
 if(isReviewer){for(let i=0;i<exceptions.length;i+=100){const ids=exceptions.slice(i,i+100).map(e=>e.id);for(const r of await rows(exceptionRepeatSql(ids.length),...ids))repeatByException.set(r.exception_id,repeatSummary(r));}}
 return json({me,assets:assets.map(decode),users:users.map(decode),records:records.map(r=>({...r,snapshot:JSON.parse(r.snapshot)})),exceptions:exceptions.map(e=>({...decode(e),latestRepeat:repeatByException.get(e.id)||null})),actions:actions.map(decode),audit:audit.map(decode),temperatureSettings,today:centralDay()});
 }catch(e){return fail(e)}}
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Problem('Please refresh ClinicalQC and try again.',403);
 const b:any=await req.json();if(JSON.stringify(b).length>32000)throw new Problem('This entry is too long.');
 const me=await operator();
 if(b.op==='saveTemperatureSettings')return json({ok:true,temperatureSettings:await saveTemperatureSettings(b.value,me)});
 if(b.op==='loadDepartments'){
 admin(me);const existing=await rows("SELECT asset_key FROM assets WHERE kind='department'");const keys=new Set(existing.map(a=>a.asset_key));const missing=REFERENCE_DEPARTMENTS.filter(label=>!keys.has(label.toLowerCase()));if(missing.length)await db().batch([...missing.map(label=>stmt('INSERT OR IGNORE INTO assets (id,kind,asset_key,label,details,active,revision) VALUES (?,?,?,?,?,1,1)',uid(),'department',label.toLowerCase(),label,JSON.stringify({source:'Current Qualtrics department list reviewed September 29, 2026'}))),auditStmt(me,'departments','Department list added',{names:missing})]);return json({ok:true,count:missing.length});
 }
 if(b.op==='saveUser'){
 admin(me);const x=b.value;const id=x.id||uid(),old=await one('SELECT * FROM operators WHERE id=?',id);
 const name=required(x.name,'Name'),email=required(x.email,'Email').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Problem('Enter a valid email address.');
 if(old&&old.email!==email&&await one('SELECT operator_id FROM qc_login_links WHERE operator_id=?',id))throw new Problem('An activated login email cannot be changed here. Keep this person’s verified sign-in email.',409);
 if(!['operator','supervisor','admin'].includes(x.role)||!['pending','verified','suspended'].includes(x.credential_status))throw new Problem('Select a valid role and credential status.');
 if(id===me.id&&(!x.active||x.role!=='admin'||email!==me.email))throw new Problem('Keep your own administrator account active with its existing email.');
 const networkId=typeof x.network_id==='string'&&x.network_id.trim()?x.network_id.trim().toLowerCase():null;if(networkId&&!/^[a-z0-9._-]{2,80}$/.test(networkId))throw new Problem('Network ID may contain letters, numbers, periods, underscores, or hyphens.');
 const expires=date(x.expires,'credential valid until',x.credential_status!=='verified'),validSince=date(x.validSince||x.competencyDate,'credential valid since',x.credential_status!=='verified');
 const competencyDate=date(x.competencyDate,'competency assessment date',true);if(competencyDate&&competencyDate>centralDay())throw new Problem('Competency assessment cannot be in the future.');
 if(validSince&&expires&&validSince>expires)throw new Problem('Valid until must be on or after valid since.');
 if(x.credential_status==='verified')required(x.credentialRef,'Credential / competency reference');
 const details=JSON.stringify({...JSON.parse(old?.details||'{}'),employeeId:x.employeeId||'',credentialRef:x.credentialRef||'',competencyDate:competencyDate||'',validSince:validSince||'',notes:x.notes||''});
 const changedCredential=!old||old.credential_status!==x.credential_status||old.expires!==expires||JSON.parse(old.details).validSince!==validSince||JSON.parse(old.details).credentialRef!==x.credentialRef||JSON.parse(old.details).competencyDate!==x.competencyDate;
 const verifier=x.credential_status==='verified'?(changedCredential?me.id:old.verified_by):null;const verifiedAt=x.credential_status==='verified'?(changedCredential?now():old.verified_at):null;
 if(old){if(old.revision!==x.revision)throw new Problem('This user changed. Refresh and reopen the form.',409);await db().batch([stmt('UPDATE operators SET network_id=?,name=?,email=?,role=?,active=?,credential_status=?,expires=?,details=?,verified_by=?,verified_at=?,revision=revision+1,auth_id=CASE WHEN email=? THEN auth_id ELSE NULL END WHERE id=? AND revision=?',networkId,name,email,x.role,x.active?1:0,x.credential_status,expires,details,verifier,verifiedAt,email,id,x.revision),auditStmt(me,id,'User updated',{before:old,after:{...x,verifiedBy:verifier}},`user:${id}:${x.revision}`)]);}else await db().batch([stmt('INSERT INTO operators (id,network_id,email,name,role,active,credential_status,expires,details,verified_by,verified_at,revision) VALUES (?,?,?,?,?,?,?,?,?,?,?,1)',id,networkId,email,name,x.role,x.active?1:0,x.credential_status,expires,details,verifier,verifiedAt),auditStmt(me,id,'User added',x)]);
 return json({ok:true});
 }
 if(b.op==='saveAsset'){
 admin(me);const x=b.value;const id=x.id||uid(),kind=x.kind;const old=await one('SELECT * FROM assets WHERE id=?',id);if(old&&old.kind!==kind)throw new Problem('Asset type cannot change.');
 if(!['department','location','truck','device','strip','low','high','range'].includes(kind))throw new Problem('Invalid item type.');const active=x.active?1:0;let label=kind==='range'?'range':required(x.label,'Name'),key=label.toLowerCase();let v:any={};
 if(kind==='location'){if(x.departmentId&&!(await one("SELECT id FROM assets WHERE id=? AND kind='department' AND active=1",x.departmentId)))throw new Problem('Select an active county / department.');v={departmentId:x.departmentId||'',description:x.description||''};}
 const region=normalizeRegion(x.region);if(['department','truck'].includes(kind)&&region&&!REGIONS.some(r=>r===region))throw new Problem('Select North, South, East, West, Central, or Perry for the region.');
 if(kind==='department')v={region,source:old?decode(old).source||'Administrator':'Administrator'};
 if(['truck','device'].includes(kind)){required(x.departmentId,'County / department');if(!(await one("SELECT id FROM assets WHERE id=? AND kind='department' AND active=1",x.departmentId)))throw new Problem('Select an active county / department.');}
 if(kind==='truck'){v={departmentId:x.departmentId,region,station:x.station||''};if(old&&decode(old).departmentId!==x.departmentId&&(await rows("SELECT id FROM assets WHERE kind='device' AND json_extract(details,'$.truckId')=?",id)).length)throw new Problem('Unassign this truck’s devices before moving it to another department.');}

 if(['truck','location'].includes(kind)){const materials=x.temperatureMaterials||'both';if(!['both','reagents','strips'].includes(materials))throw new Problem('Select the supplies stored at this location.');v={...v,temperatureMaterials:materials};}
 if(kind==='device'){const before=old?JSON.parse(old.details):{};v={...before,departmentId:x.departmentId,serial:required(x.serial,'Serial number').replace(/\s+/g,' '),model:before.meterImport&&!x.model?'':required(x.model,'Device model'),truckId:x.truckId||'',status:x.status||'active'};key=meterSerialKey(v.serial);if((await rows("SELECT * FROM assets WHERE kind='device' AND id!=?",id)).some(a=>meterSerialKey(decode(a).serial||a.asset_key)===key))throw new Problem('This serial number is already registered.',409);if(!['active','hold','retired'].includes(v.status))throw new Problem('Select a valid device status.');if(v.truckId&&!(await one("SELECT id FROM assets WHERE id=? AND kind='truck' AND active=1",v.truckId)))throw new Problem('Select an active truck.');if(v.truckId&&decode(await one('SELECT * FROM assets WHERE id=?',v.truckId)).departmentId!==x.departmentId)throw new Problem('The assigned truck must belong to the device’s department.');if(old&&JSON.parse(old.details).status==='hold'&&v.status==='active')throw new Problem('Use Return to service in the device list after exception review.');}
 if(['strip','low','high'].includes(kind)){v={model:required(x.model,'Compatible device model'),lot:required(x.lot,'Lot number'),expires:date(x.expires,'expiration'),opened:date(x.opened,'opened date',true),discard:date(x.discard,'discard date',true)};key=[v.model,v.lot].join('|').toLowerCase();if(v.opened&&v.discard&&v.discard<v.opened)throw new Problem('Discard date must be on or after the opened date.');if(v.opened&&v.expires<v.opened)throw new Problem('Opened date must not follow expiration.');}
 if(kind==='range'){const strip=await one("SELECT * FROM assets WHERE id=? AND kind='strip'",x.stripId),control=await one("SELECT * FROM assets WHERE id=? AND kind IN ('low','high')",x.controlId);if(!strip||!control)throw new Problem('Select the strip and control lots.');if(!sameDeviceModel(decode(strip).model,decode(control).model))throw new Problem('Strip and control models must match.');if(x.min===''||x.max===''||!Number.isFinite(Number(x.min))||!Number.isFinite(Number(x.max))||Number(x.min)<0||Number(x.min)>=Number(x.max))throw new Problem('Range minimum must be below maximum, with nonnegative numeric values.');if(!['mg/dL','mmol/L'].includes(x.units))throw new Problem('Select measurement units.');v={stripId:x.stripId,controlId:x.controlId,min:Number(x.min),max:Number(x.max),units:x.units,source:required(x.source,'Control range reference'),level:control.kind};key=[v.stripId,v.controlId].join('|');label=`${decode(strip).lot} / ${decode(control).lot} · ${control.kind}`;}
 if(old){if(old.revision!==x.revision)throw new Problem('This item changed. Refresh and reopen the form.',409);await db().batch([stmt('UPDATE assets SET label=?,asset_key=?,details=?,active=?,revision=revision+1 WHERE id=? AND revision=?',label,key,JSON.stringify(v),active,id,x.revision),auditStmt(me,id,'Inventory updated',{before:old,after:{...v,label,active}},`asset:${id}:${x.revision}`)]);}else await db().batch([stmt('INSERT INTO assets (id,kind,asset_key,label,details,active,revision) VALUES (?,?,?,?,?,?,1)',id,kind,key,label,JSON.stringify(v),active),auditStmt(me,id,'Inventory added',{...v,label,kind,active})]);return json({ok:true});
 }
 if(b.op==='submitQC'){
 const x=b.value;required(x.requestId,'Submission ID');const existing=await one('SELECT id,operator_id,status FROM records WHERE id=?',x.requestId);if(existing){if(existing.operator_id!==me.id)throw new Problem('Invalid submission ID.',409);return json({ok:true,id:existing.id,status:existing.status})}
 const identifier=required(x.networkId,'User ID or email').toLowerCase();if(![me.network_id,me.email].filter(Boolean).map((v:string)=>v.toLowerCase()).includes(identifier))throw new Problem('The user ID or email must match your signed-in, credentialed account.',403);
 if(!credentialValid(me)){
 const id=uid(),ts=now();await db().batch([stmt('INSERT INTO exceptions (id,operator_id,category,title,status,created_at,updated_at,details) VALUES (?,?,?,?,?,?,?,?)',id,me.id,'credential','Testing attempt without current verified credentials','open',ts,ts,JSON.stringify({operatorName:me.name,credentialStatus:me.credential_status,expires:me.expires})),auditStmt(me,id,'Testing blocked: credentials not current',{})]);throw new Problem('Your testing credentials are not current and verified. An exception was sent for administrator review.',403);}
 const fetchAsset=async(id:string,kind:string)=>{const r=await one('SELECT * FROM assets WHERE id=? AND kind=? AND active=1',id,kind);if(!r)throw new Problem('Select an active '+kind+' item.');return decode(r)};
 const [device,strip,low,high,truck,department]=await Promise.all([fetchAsset(x.deviceId,'device'),fetchAsset(x.stripId,'strip'),fetchAsset(x.lowId,'low'),fetchAsset(x.highId,'high'),fetchAsset(x.truckId,'truck'),fetchAsset(x.departmentId,'department')]);
 if(truck.departmentId!==department.id||device.departmentId!==department.id)throw new Problem('The truck and device must belong to the selected county / department.');
 let seriesId=x.requestId,repeatParent:any;if(x.repeatOf){const parent=await one('SELECT * FROM records WHERE id=?',x.repeatOf);if(!parent||parent.device_id!==device.id||['historical_superseded','historical_excluded'].includes(parent.status))throw new Problem('Repeat QC must reference an existing check on this device.');const previous=JSON.parse(parent.snapshot);if(previous.historical)throw new Problem('Record a new QC check for this device.');if(previous.department?.id&&previous.department.id!==department.id)throw new Problem('This device changed departments. Record a new QC check.');if(previous.truck?.id!==truck.id)throw new Problem('The truck changed. Record a new QC check with that truck.');seriesId=previous.input.seriesId||parent.id;repeatParent={id:parent.id,snapshot:previous};}
 if(!deviceModelKey(device.model))throw new Problem('Add the device manufacturer and model in Devices before recording QC.');
 if(device.status==='retired')throw new Problem('This device has been retired.');
 const ran=await rows("SELECT * FROM assets WHERE kind='range' AND active=1");const ranges=ran.map(decode);const lr=controlRange('low',ranges,strip.id,low.id),hr=controlRange('high',ranges,strip.id,high.id);
 for(const k of ['low','high']){x[k+'Error']=typeof x[k+'Error']==='string'?x[k+'Error'].trim():'';if(x[k+'Error'].length>250)throw new Problem('Device error is too long.');if(!x[k+'Error']&&(typeof x[k+'Value']!=='number'||!Number.isFinite(x[k+'Value'])||x[k+'Value']<0))throw new Problem('Enter both control readings, or a device error for each missing reading.');if(x[k+'Error']&&x[k+'Value']!==null)throw new Problem('Enter a reading or a device error for each level, not both.');}
 if(typeof x.clean!=='boolean'||typeof x.stored!=='boolean'||x.attested!==true)throw new Problem('Complete the preparation checks and attestation.');
 const observed=new Date(x.occurredAt);if(Number.isNaN(observed.getTime())||observed.getTime()>Date.now()+60000)throw new Problem('Enter a valid test time that is not in the future.');
 if(centralDay(observed)!==centralDay())throw new Problem('Record today’s QC using Central time. Earlier records need administrator review.');
 const result=evaluateQC(device,strip,low,high,lr,hr,x);const ts=now(),id=x.requestId;
 const temperatureSettings=await getTemperatureSettings();const temp=qcTemperature(x.temperature,truck,me,centralDay(observed),id,temperatureSettings,repeatParent);
 const {temperature:submittedTemperature,repeatTemperature,temperatureCapture:clientTemperatureCapture,...qcInput}=x;
 const snapshot={temperature:temp.snapshot,temperatureCapture:temp.capture,department,device,strip,low,high,lowRange:lr||null,highRange:hr||null,truck,operator:{identifier:me.network_id||me.email,identifierType:me.network_id?'network_id':'email',networkId:me.network_id,id:me.id,name:me.name,email:me.email,employeeId:me.employeeId,credentialStatus:me.credential_status,credentialRef:me.credentialRef,validSince:me.validSince||me.competencyDate,expires:me.expires,verifiedBy:me.verified_by,verifiedAt:me.verified_at},input:{...qcInput,...(temp.capture.mode==='recorded'?{temperature:submittedTemperature}:{}),networkId:me.network_id||me.email,seriesId,occurredAt:observed.toISOString()},...result};
 const ops=[stmt('INSERT INTO records (id,operator_id,device_id,occurred_at,created_at,status,snapshot) VALUES (?,?,?,?,?,?,?)',id,me.id,device.id,observed.toISOString(),ts,result.status,JSON.stringify(snapshot)),auditStmt(me,id,'QC recorded',{status:result.status,issues:result.issues,temperatureCapture:temp.capture})];
 if(result.issues.length){const exId=uid();ops.push(stmt('INSERT INTO exceptions (id,record_id,device_id,operator_id,category,title,status,created_at,updated_at,details) VALUES (?,?,?,?,?,?,?,?,?,?)',exId,id,device.id,me.id,'qc',result.issues[0],'open',ts,ts,JSON.stringify({issues:result.issues,operatorName:me.name,deviceSerial:device.serial,truckLabel:truck.label,departmentId:department.id,departmentLabel:department.label})));ops.push(stmt('UPDATE assets SET details=json_set(details,\'$.status\',\'hold\'),revision=revision+1 WHERE id=?',device.id));}
 await db().batch([...ops,...temp.statements,...qcDeviceLocationStatements(db(),id,me,ts)]);return json({ok:true,id,status:result.status,issues:result.issues});
 }
 if(b.op==='reviewException'){
 review(me);const x=b.value,ex=await one('SELECT * FROM exceptions WHERE id=?',x.id);if(!ex||ex.status==='excluded')throw new Problem('Exception not found.',404);if(ex.revision!==x.revision)throw new Problem('This exception changed. Refresh to see the latest review.',409);
 if(me.role==='supervisor'&&ex.assignee!==me.id)throw new Problem('Only the assigned supervisor can update this exception.',403);
 const action=required(x.action,'Action');let notes:string;if(x.decision!==undefined){try{notes=reviewNotes(x.decision,x.notes)}catch(e){throw new Problem((e as Error).message)}}else{notes=required(x.notes,'Review or completion notes');}const allowed=['Review and document','Assign remedial education','Request repeat QC','Replace test strips','Replace control solution','Remove device from service','Escalate for review','Document completion','Close exception','Reopen exception'];if(!allowed.includes(action))throw new Problem('Select a review action.');
 if(me.role!=='admin'&&!['Document completion','Review and document','Close exception'].includes(action))throw new Problem('Only an administrator can assign or reopen exceptions or change the required action.',403);
 if(x.clearDeviceHold!==undefined&&typeof x.clearDeviceHold!=='boolean')throw new Problem('Choose whether to clear the device hold.');
 if(x.clearDeviceHold&&action!=='Close exception')throw new Problem('Clear device hold is available only when closing an exception.');
 if(ex.status==='closed'&&action!=='Reopen exception')throw new Problem('Reopen the exception before adding another action.');
 let assignee=ex.assignee,due=ex.due,status=ex.status;
 if(me.role==='admin'){assignee=x.assignee||null;due=date(x.due,'follow-up due date',true);if(assignee&&!(await one("SELECT id FROM operators WHERE id=? AND active=1 AND role IN ('supervisor','admin')",assignee)))throw new Problem('Select an active supervisor or administrator.');}
 if(action==='Assign remedial education'&&(!assignee||!due))throw new Problem('Select a supervisor and due date for remedial education.');
 if(action==='Close exception')status='closed';else if(action==='Reopen exception')status='open';else if(action==='Document completion')status='awaiting_review';else status=assignee?'assigned':'in_review';
 if(x.clearDeviceHold)return json(await closeExceptionAndRelease(me,ex,notes,assignee,due));
 const ts=now(),ops=[stmt('UPDATE exceptions SET status=?,assignee=?,due=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=?',status,assignee,due,ts,ex.id,x.revision),stmt('INSERT INTO actions (id,exception_id,actor_id,actor_name,created_at,action,notes,details) VALUES (?,?,?,?,?,?,?,?)',uid(),ex.id,me.id,me.name,ts,action,notes,JSON.stringify({assignee,due,status})),auditStmt(me,ex.id,action,{notes,assignee,due,status},`exception:${ex.id}:${x.revision}`)];
 if(action==='Remove device from service'&&ex.device_id)ops.push(stmt("UPDATE assets SET details=json_set(details,'$.status','hold'),revision=revision+1 WHERE id=?",ex.device_id));await db().batch(ops);return json({ok:true});
 }
 if(b.op==='releaseDevice'){
 admin(me);const notes=required(b.notes,'Return-to-service notes');const d=await one("SELECT * FROM assets WHERE id=? AND kind='device'",b.id);if(!d)throw new Problem('Device not found.');if(JSON.parse(d.details).status!=='hold')throw new Problem('Only held devices can be returned to service.');const pending=await one("SELECT count(*) AS n FROM exceptions WHERE device_id=? AND status!='closed'",b.id);if(pending.n)throw new Problem('Close this device’s open exceptions before returning it to service.');const latest=await one('SELECT * FROM records WHERE device_id=? ORDER BY created_at DESC LIMIT 1',b.id);if(!latest||latest.status!=='pass'||centralDay(new Date(latest.occurred_at))!==centralDay())throw new Problem('A passing low and high QC from today is required before release.');await db().batch([stmt("UPDATE assets SET details=json_set(details,'$.status','active'),revision=revision+1 WHERE id=? AND NOT EXISTS (SELECT 1 FROM exceptions WHERE device_id=? AND status!='closed') AND (SELECT status FROM records WHERE device_id=? ORDER BY created_at DESC LIMIT 1)='pass'",b.id,b.id,b.id),auditStmt(me,b.id,'Device returned to service',{notes,recordId:latest.id})]);return json({ok:true});
 }
 throw new Problem('Unknown action.');
 }catch(e){return fail(e)}}
