import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const operators = sqliteTable('operators', {
 id:text('id').primaryKey(), authId:text('auth_id'), networkId:text('network_id'), email:text('email').notNull(), name:text('name').notNull(), role:text('role').notNull(), active:integer('active').notNull().default(1), credentialStatus:text('credential_status').notNull().default('pending'), expires:text('expires'), details:text('details').notNull().default('{}'), verifiedBy:text('verified_by'), verifiedAt:text('verified_at'), revision:integer('revision').notNull().default(1)
}, t=>[uniqueIndex('operators_email').on(t.email),uniqueIndex('operators_auth').on(t.authId),uniqueIndex('operators_network_id').on(t.networkId)]);
export const assets=sqliteTable('assets',{id:text('id').primaryKey(),kind:text('kind').notNull(),assetKey:text('asset_key').notNull(),label:text('label').notNull(),details:text('details').notNull(),active:integer('active').notNull().default(1),revision:integer('revision').notNull().default(1)},t=>[uniqueIndex('assets_kind_key').on(t.kind,t.assetKey),index('assets_kind').on(t.kind)]);
export const records=sqliteTable('records',{id:text('id').primaryKey(),operatorId:text('operator_id').notNull(),deviceId:text('device_id').notNull(),occurredAt:text('occurred_at').notNull(),createdAt:text('created_at').notNull(),status:text('status').notNull(),snapshot:text('snapshot').notNull()},t=>[index('records_occurred_at').on(t.occurredAt),index('records_device_time').on(t.deviceId,t.createdAt),index('records_operator_time').on(t.operatorId,t.createdAt)]);
export const exceptions=sqliteTable('exceptions',{id:text('id').primaryKey(),recordId:text('record_id'),deviceId:text('device_id'),operatorId:text('operator_id').notNull(),category:text('category').notNull(),title:text('title').notNull(),status:text('status').notNull().default('open'),assignee:text('assignee'),due:text('due'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),details:text('details').notNull(),revision:integer('revision').notNull().default(1)},t=>[index('exceptions_status').on(t.status),index('exceptions_assignee').on(t.assignee)]);
export const actions=sqliteTable('actions',{id:text('id').primaryKey(),exceptionId:text('exception_id').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),createdAt:text('created_at').notNull(),action:text('action').notNull(),notes:text('notes').notNull(),details:text('details').notNull()},t=>[index('actions_exception').on(t.exceptionId)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),createdAt:text('created_at').notNull(),entityId:text('entity_id').notNull(),event:text('event').notNull(),details:text('details').notNull()},t=>[index('audit_time').on(t.createdAt)]);
export const importBatches=sqliteTable('import_batches',{id:text('id').primaryKey(),fileHash:text('file_hash').notNull(),filename:text('filename').notNull(),createdAt:text('created_at').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),sourceRows:integer('source_rows').notNull(),importedRows:integer('imported_rows').notNull(),skippedRows:integer('skipped_rows').notNull(),recordCount:integer('record_count').notNull(),details:text('details').notNull()},t=>[uniqueIndex('import_batches_hash').on(t.fileHash)]);
export const historyRows=sqliteTable('history_rows',{fingerprint:text('fingerprint').primaryKey(),identityKey:text('identity_key').notNull(),batchId:text('batch_id').notNull(),recordId:text('record_id').notNull(),sourceRow:integer('source_row').notNull()},t=>[uniqueIndex('history_rows_identity').on(t.identityKey)]);
export const temperatureRecords=sqliteTable('temperature_records',{id:text('id').primaryKey(),locationId:text('location_id').notNull(),qcRecordId:text('qc_record_id'),operatorId:text('operator_id').notNull(),observedDate:text('observed_date').notNull(),createdAt:text('created_at').notNull(),status:text('status').notNull(),snapshot:text('snapshot').notNull()},t=>[index('temperature_date').on(t.observedDate),index('temperature_operator').on(t.operatorId)]);
export const applicationSettings=sqliteTable('application_settings',{id:text('id').primaryKey(),details:text('details').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull()});
